name: to_do
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  another_flushbar: ^1.12.32
  cloud_firestore: ^6.1.0
  dartz: ^0.10.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  fluttertoast: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  image_picker: ^1.2.1
  injectable: ^2.4.1
  motion_toast: ^2.14.0
  provider: ^6.1.5+1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
